lsi: false
safe: true
source: mark-hurlstone/QJEP-Special-Issue-Baddley-Hitch-WM-Model
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
